apiVersion: v1
kind: ServiceAccount
metadata:
  name: agents-app
  namespace: agents
  annotations:
    eks.amazonaws.com/role-arn: "${APP_ROLE_ARN}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: agents
  annotations:
    eks.amazonaws.com/role-arn: "${ADOT_ROLE_ARN}"
